name: Upload Huey

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: huey
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Bazar/liveries/uh-1h/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
